### ISSUE TITLE
Codesign doesn't work well

### ISSUE THREAD

**Issue by moreal** [planetarium/homebrew-brew#41]
# Log

```
$ brew install planetarium/brew/planet --verbose --debug
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading planetarium/brew/planet
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading planetarium/brew/planet
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading planetarium/brew/planet
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/planetarium/libplanet/releases/download/5.0.0/planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.8\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/planetarium/libplanet/releases/download/5.0.0/planet-5.0.0-osx-arm64.tar.xz
Already downloaded: /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
==> /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz is quarantined
==> Verifying checksum for '7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz'
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/usr/bin/env tar --list --file /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
All dependencies satisfied.
==> Installing Cask planet
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env tar --extract --no-same-owner --file /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz --directory /private/tmp/homebrew-unpack20240704-70232-n5ta4v
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Store.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Store.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/planet /opt/homebrew/Caskroom/planet/5.0.0/planet
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/native/. /opt/homebrew/Caskroom/planet/5.0.0/native
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/libsecp256k1.dylib /opt/homebrew/Caskroom/planet/5.0.0/libsecp256k1.dylib
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Crypto.Secp256k1.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Crypto.Secp256k1.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Net.xml /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Net.xml
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Extensions.Cocona.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Extensions.Cocona.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Common.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Common.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Stun.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Stun.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.xml /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.xml
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Crypto.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Crypto.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Action.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Action.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/librocksdb.dylib /opt/homebrew/Caskroom/planet/5.0.0/librocksdb.dylib
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/planet.pdb /opt/homebrew/Caskroom/planet/5.0.0/planet.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Net.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Net.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.Types.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Types.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-70232-n5ta4v/Libplanet.RocksDBStore.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.RocksDBStore.pdb
==> Verifying Gatekeeper status of /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
==> /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz is quarantined
==> Propagating quarantine from /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz to /opt/homebrew/Caskroom/planet/5.0.0
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/moreal/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;66861191\;Homebrew\\x20Cask\;5D152781-129E-4456-9CBC-60E8CC880475
==> Creating metadata directory: /opt/homebrew/Caskroom/planet/.metadata/5.0.0/20240704044435.272
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/planet/.metadata/5.0.0/20240704044435.272/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'planet' to '/opt/homebrew/bin/planet'
/usr/bin/env /bin/ln -h -f -s -- /opt/homebrew/Caskroom/planet/5.0.0/planet /opt/homebrew/bin/planet
==> Installing artifact of class Cask::Artifact::PostflightBlock
/usr/bin/env echo Hello
/usr/bin/env /bin/chmod -R -- 0755 /opt/homebrew/Caskroom/planet/5.0.0/planet
/usr/bin/env /opt/homebrew/Caskroom/planet/5.0.0/planet --completion bash
==> Reverting installation of artifact of class Cask::Artifact::Binary
==> Unlinking Binary '/opt/homebrew/bin/planet'
==> Purging files for version 5.0.0 of Cask planet
Error: Failure while executing; `/usr/bin/env /opt/homebrew/Caskroom/planet/5.0.0/planet --completion bash` was terminated by uncaught signal KILL.
/opt/homebrew/Library/Homebrew/system_command.rb:352:in `assert_success!'
/opt/homebrew/Library/Homebrew/system_command.rb:75:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/opt/homebrew/Library/Homebrew/cask/dsl/base.rb:21:in `system_command'
/opt/homebrew/Library/Taps/planetarium/homebrew-brew/Casks/planet.rb:35:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:26:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:248:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:241:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

**Comment by boscohyun** [comment]
same here.

```
brew install planetarium/brew/planet --verbose --debug
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading planetarium/brew/planet
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading planetarium/brew/planet
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading planetarium/brew/planet
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.8-71-g21ba72b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/planetarium/libplanet/releases/download/5.0.0/planet-5.0.0-osx-arm64.tar.xz
==> Downloading https://github.com/planetarium/libplanet/releases/download/5.0.0/planet-5.0.0-osx-arm64.tar.xz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/158087990/230162a0-b0af-4ae5-90a4-78bb05f51fa0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240704%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240704T092815Z&X-Amz-Expires=300&X-Amz-Signature=f41433edccc0da0d51b29841d89b13722c68c675dcc37f75ca674cf0b86bd50a&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=158087990&response-content-disposition=attachment%3B%20filename%3Dplanet-5.0.0-osx-arm64.tar.xz&response-content-type=application%2Foctet-stream
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.8-71-g21ba72b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz.incomplete --location https://objects.githubusercontent.com/github-production-release-asset-2e65be/158087990/230162a0-b0af-4ae5-90a4-78bb05f51fa0\?X-Amz-Algorithm=AWS4-HMAC-SHA256\&X-Amz-Credential=releaseassetproduction\%2F20240704\%2Fus-east-1\%2Fs3\%2Faws4_request\&X-Amz-Date=20240704T092815Z\&X-Amz-Expires=300\&X-Amz-Signature=f41433edccc0da0d51b29841d89b13722c68c675dcc37f75ca674cf0b86bd50a\&X-Amz-SignedHeaders=host\&actor_id=0\&key_id=0\&repo_id=158087990\&response-content-disposition=attachment\%3B\%20filename\%3Dplanet-5.0.0-osx-arm64.tar.xz\&response-content-type=application\%2Foctet-stream
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.4M  100 30.4M    0     0  9880k      0  0:00:03  0:00:03 --:--:-- 9881k
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
==> /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz is not quarantined
==> Quarantining /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz https://github.com/planetarium/libplanet/releases/download/5.0.0/planet-5.0.0-osx-arm64.tar.xz https://libplanet.io/
==> Verifying checksum for '7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz'
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/usr/bin/env tar --list --file /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
All dependencies satisfied.
==> Installing Cask planet
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env tar --extract --no-same-owner --file /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz --directory /private/tmp/homebrew-unpack20240704-16073-ld9iop
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Store.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Store.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/planet /opt/homebrew/Caskroom/planet/5.0.0/planet
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/native/. /opt/homebrew/Caskroom/planet/5.0.0/native
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/libsecp256k1.dylib /opt/homebrew/Caskroom/planet/5.0.0/libsecp256k1.dylib
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Crypto.Secp256k1.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Crypto.Secp256k1.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Net.xml /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Net.xml
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Extensions.Cocona.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Extensions.Cocona.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Common.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Common.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Stun.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Stun.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.xml /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.xml
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Crypto.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Crypto.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Action.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Action.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/librocksdb.dylib /opt/homebrew/Caskroom/planet/5.0.0/librocksdb.dylib
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/planet.pdb /opt/homebrew/Caskroom/planet/5.0.0/planet.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Net.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Net.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.Types.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.Types.pdb
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240704-16073-ld9iop/Libplanet.RocksDBStore.pdb /opt/homebrew/Caskroom/planet/5.0.0/Libplanet.RocksDBStore.pdb
==> Verifying Gatekeeper status of /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
==> /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz is quarantined
==> Propagating quarantine from /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz to /opt/homebrew/Caskroom/planet/5.0.0
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/seungmin/Library/Caches/Homebrew/downloads/7c4001bf88b65fe58f9a7599f7d1de21b1466625a8c7f69a68f15befe508a00f--planet-5.0.0-osx-arm64.tar.xz
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;66866b34\;Homebrew\\x20Cask\;8531AF87-167E-4641-8DCA-ADC508F415DB
==> Creating metadata directory: /opt/homebrew/Caskroom/planet/.metadata/5.0.0/20240704092823.870
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/planet/.metadata/5.0.0/20240704092823.870/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'planet' to '/opt/homebrew/bin/planet'
/usr/bin/env /bin/ln -h -f -s -- /opt/homebrew/Caskroom/planet/5.0.0/planet /opt/homebrew/bin/planet
==> Installing artifact of class Cask::Artifact::PostflightBlock
/usr/bin/env /bin/chmod -R -- 0755 /opt/homebrew/Caskroom/planet/5.0.0/planet
/usr/bin/env /opt/homebrew/Caskroom/planet/5.0.0/planet --completion bash
==> Reverting installation of artifact of class Cask::Artifact::Binary
==> Unlinking Binary '/opt/homebrew/bin/planet'
==> Purging files for version 5.0.0 of Cask planet
Error: Failure while executing; `/usr/bin/env /opt/homebrew/Caskroom/planet/5.0.0/planet --completion bash` was terminated by uncaught signal KILL.
/opt/homebrew/Library/Homebrew/system_command.rb:352:in `assert_success!'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/call_validation_2_7.rb:652:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/call_validation_2_7.rb:652:in `block in create_validator_procedure_fast0'
/opt/homebrew/Library/Homebrew/system_command.rb:75:in `run!'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
/opt/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/opt/homebrew/Library/Homebrew/cask/dsl/base.rb:21:in `system_command'
/opt/homebrew/Library/Taps/planetarium/homebrew-brew/Casks/planet.rb:34:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:26:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:248:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:241:in `install_artifacts'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11466/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

<img width="273" alt="image" src="https://github.com/planetarium/homebrew-brew/assets/6128868/2239f6e9-173c-4fa7-b147-16ffc2830a3e">

**Comment by eseiker** [comment]
I got the same message also with manual codesign, but I think it might be not a codesign issue.
Could you try another shot with `brew upgrade planetarium/brew/planet --no-quarantine` or `xattr -d com.apple.quarantine planet` on the codesigned binary?
If this works, adding xattr -d in postflight might work hopefully

**Comment by Atralupus** [comment]
We need [notarizing](https://developer.apple.com/documentation/security/notarizing-macos-software-before-distribution?language=objc)
